repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        # Allow up to 50 MB and ignore PDFs under docs/requirements/
        args: ["--maxkb=51200"]
        exclude: '^docs/requirements/.*\.(pdf|PDF)$'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.7
          - pydantic-settings>=2.2.1
          - types-PyYAML>=6.0.12.20240808
          - sqlmodel>=0.0.24
          - sqlalchemy>=2.0.43
