repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Known-good tag; if a newer one exists, we can autoupdate later.
    rev: v0.6.4
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.7
          - pydantic-settings>=2.2.1
          - types-PyYAML>=6.0.12.20240808
          - sqlmodel>=0.0.24
          - sqlalchemy>=2.0.43
