name: CI - Tests & Coverage

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install deps
        run: |
          uv lock
          uv sync --dev

      - name: Lint & typecheck
        run: |
          uv run ruff check .
          uv run ruff format --check .
          uv run mypy .

      - name: Tests with coverage (gated)
        run: |
          uv run pytest -q \
            --cov=poke_pricer \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-fail-under=85

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: error
