name: ci

on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Sync deps
        run: |
          uv venv
          uv sync --dev
      - name: Lint
        run: |
          uv run ruff check .
          uv run ruff format .
      - name: Type-check
        run: uv run mypy .
      - name: Test
        run: uv run pytest -q
