name: Release Freeze (until MVP)

on:
  release:
    types: [created, published]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Fail and delete the release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          TAG: ${{ github.event.release.tag_name }}
          REL_ID: ${{ github.event.release.id }}
        run: |
          echo "::error::Releases are frozen until MVP. Deleting release '${TAG}'."
          gh release delete "${TAG}" --repo "${REPO}" -y || true
          exit 1
